mysite/blog/urls.py
# blog/urls.py

from django.urls import path

from blog.views import IndexView, PostDetailView, CategoryListView, TagListView,CategoryPostView, TagPostView,SearchPostView

app_name = 'blog'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('tags/', TagListView.as_view(), name='tag_list'),
    path('category/<str:category_slug>/',
         CategoryPostView.as_view(), name='category_post'),
    path('tag/<str:tag_slug>/', TagPostView.as_view(), name='tag_post'),
    path('search/', SearchPostView.as_view(), name='search_post'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
# blog/models.py

from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, blank=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)
    is_public = models.BooleanField(default=False)
    image = models.ImageField(
        upload_to='post_images/', null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if self.is_public and not self.published_at:
            self.published_at = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class ContentImage(models.Model):
    post = models.ForeignKey(Post, on_delete=models.PROTECT)
    content_image = models.ImageField(upload_to='post_content_images/')

mysite/blog/views.py
# blog/views.py

from django.db.models import Count, Q
from django.http import Http404
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404

from blog.models import Post, Category, Tag


class PostDetailView(DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset=queryset)
        if not obj.is_public and not self.request.user.is_authenticated:
            raise Http404
        return obj


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = 1


class CategoryListView(ListView):
    queryset = Category.objects.annotate(
        num_posts=Count('post', filter=Q(post__is_public=True)))


class TagListView(ListView):
    queryset = Tag.objects.annotate(num_posts=Count(
        'post', filter=Q(post__is_public=True)))





class CategoryPostView(ListView):
    model = Post
    template_name = 'blog/category_post.html'

    def get_queryset(self):
        category_slug = self.kwargs['category_slug']
        self.category = get_object_or_404(Category, slug=category_slug)
        qs = super().get_queryset().filter(category=self.category)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context




class TagPostView(ListView):
    model = Post
    template_name = 'blog/tag_post.html'

    def get_queryset(self):
        tag_slug = self.kwargs['tag_slug']
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = super().get_queryset().filter(tags=self.tag)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context



class SearchPostView(ListView):
    model = Post
    template_name = 'blog/search_post.html'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q', None)
        lookups = (
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(category__name__icontains=query) |
            Q(tags__name__icontains=query)
        )
        if query is not None:
            qs = super().get_queryset().filter(lookups).distinct()
            return qs
        qs = super().get_queryset()
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query
        return context

mysite/blog/templates/blog/category_list.html
<!-- blog/category_list.html -->
{% extends "base.html" %}

{% block title %}カテゴリ一覧 | 青葉山の猫{% endblock %}
{% block description %}マイブログです。毎日更新します。{% endblock %}

{% block content %}
<h1>カテゴリ一覧</h1>
<ul>
  {% for category in object_list %}
  <li><a href="{% url 'blog:category_post' category.slug %}">{{ category.name }} ({{ category.num_posts }})</a></li>
  {% empty %}
  <li>カテゴリはありません。</li>
  {% endfor %}
</ul>
{% endblock %}

mysite/blog/templates/blog/category_post.html
<!-- blog/category_post.html -->

{% extends "base.html" %}

{% block title %}「{{ category.name }}」の投稿一覧 {% endblock %}
{% block description %}マイブログです。毎日更新します。{% endblock %}

{% block content %}
<h1>「{{ category.name }}」の投稿一覧</h1>
<ul>
  {% for post in object_list %}
  {% if user.is_authenticated or post.is_public %}
  <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></li>
  {% else %}
  <li>投稿はありません。</li>
  {% endif %}
  {% empty %}
  <li>まだ投稿はありません。</li>
  {% endfor %}
</ul>
{% endblock %}

mysite/blog/templates/blog/index.html
{% extends "base.html" %}

{% block title %}青葉山の猫 | {{ block.super }}{% endblock %}
{% block description %}マイブログです。毎日更新します。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">青葉山の猫</h1>
      <h2 class="mb-4">投稿一覧</h2>
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination.html" %}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

mysite/blog/templates/blog/index2.html
<!-- blog/index.html -->

{% extends "base.html" %}

{% load static %}
<link rel="icon" href="{% static 'img/favicon.ico' %}">
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% block title %}投稿一覧 | {{ block.super }}{% endblock %}

{% block description %}マイブログです。毎日更新します。{% endblock %}
{% block content %}

<ul>
  {% for post in object_list %}
  {% if user.is_authenticated or post.is_public %}
  <li>
  {% if not post.is_public %}[下書き] {% endif %}
  <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
  <br>
  {% if post.image %}
  <a href="{% url 'blog:post_detail' post.id %}">
    <img src="{{ post.image.url }}" alt="{{ post.title }}" width="240" height="126">
  </a>
  {% endif %}
</li>
  {% endif %}
  {% empty %}
  <li>まだ投稿はありません。</li>
  {% endfor %}
  <img src="/media/post_content_images/2dhalfchhetah.png" width="512" height="360" alt="Pipenv | Python">
</ul>
{% endblock %}



{% extends "base.html" %}

{% block title %}投稿一覧 | {{ block.super }}{% endblock %}
{% block description %}マイブログです。毎日更新します。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">投稿一覧</h1>
      {% include "blog/snippets/main_post_list.html" %}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
<!-- blog/post_detail.html -->


{% extends "base.html" %}

{% block title %}投稿 | 青葉山の猫{% endblock %}
{% block description %}マイブログです。毎日更新します。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      {% include "blog/snippets/main_post_detail.html" %}

    </main>

  </div>
</div>
{% endblock %}

mysite/blog/templates/blog/post_detail_spare.html
<!-- blog/post_detail.html -->

<h1>{{ object.title }}</h1>
<p>{{ object.published_at|date }}</p>
<p>{{ object.category.name }}</p>
{% for tag in object.tags.all %}
{{ tag.name }}
{% endfor %}
<hr>
{{ object.content|safe }}

mysite/blog/templates/blog/sample.html
<img src="/media/post_content_images/Python.jpg" width="512" height="360" alt="Pipenv | Python">

mysite/blog/templates/blog/search_post.html
<!-- blog/templates/blog/search_post.html -->

{% extends "base.html" %}

{% block title %}{% if query %}{{ query }}{% endif %} | {{ block.super }}{% endblock %}
{% block description %}検索ワード「{% if query %}{{ query }}{% endif %}」での検索結果ページです。{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <main class="col-md-8">
      <h1 class="mb-4">「{% if query %}{{ query }}{% endif %}」の検索結果</h1>
      <p class="text-right">{{ page_obj.start_index }}-{{ page_obj.end_index }}件（{{ paginator.count }}件）</p>
      {% include "blog/snippets/main_post_list.html" %}
      {% include "blog/snippets/pagination.html" %}
    </main>
    <aside class="col-md-4">
      {% include "blog/snippets/sidebar.html" %}
    </aside>
  </div>
</div>
{% endblock %}

mysite/blog/templates/blog/snippets/main_post_detail.html
<!-- blog/post_detail.html -->

<h1>{{ object.title }}</h1>
<p>{{ object.published_at|date }}</p>
<p>{{ object.category.name }}</p>
{% for tag in object.tags.all %}
{{ tag.name }}
{% endfor %}
<hr>
{{ object.content|safe }}

mysite/blog/templates/blog/snippets/main_post_list.html
<ul>
  {% for post in object_list %}
  {% if user.is_authenticated or post.is_public %}
  <li>
  {% if not post.is_public %}[下書き] {% endif %}
  <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
  <br>
  {% if post.image %}
  <a href="{% url 'blog:post_detail' post.id %}">
    <img src="{{ post.image.url }}" alt="{{ post.title }}" width="240" height="126">
  </a>
  {% endif %}
</li>
  {% endif %}
  {% empty %}
  <li>まだ投稿はありません。</li>
  {% endfor %}
  <img src="/media/post_content_images/Aobayama_cats.jpg" width="512" height="360" alt="Pipenv | Python">
</ul>

mysite/blog/templates/blog/snippets/main_tag_list.html
<h1>「#{{ tag.name }}」の投稿一覧</h1>
<ul>
  {% for post in object_list %}
  {% if user.is_authenticated or post.is_public %}
  <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></li>
  {% else %}
  <li>投稿はありません。</li>
  {% endif %}
  {% empty %}
  <li>まだ投稿はありません。</li>
  {% endfor %}

</ul>

mysite/blog/templates/blog/snippets/pagination.html
<!-- blog/templates/blog/snippets/pagination.html -->

{% if is_paginated %}
<nav>
  {% if page_obj.has_previous %}
  <a href="?page={{ page_obj.previous_page_number }}{% if query %}&q={{ query }}{% endif %}">前へ</a>
  {% endif %}

  {% for num in paginator.page_range %}
  {% if page_obj.number == num %}
  <span>{{ num }}</span>
  {% else %}
  <a href="?page={{ num }}{% if query %}&q={{ query }}{% endif %}">{{ num }}</a>
  {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}{% if query %}&q={{ query }}{% endif %}">次へ</a>
  {% endif %}
</nav>
{% endif %}

mysite/blog/templates/blog/snippets/pagination2.html
{% if is_paginated %}
<nav aria-label="Page navigation">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
    {% endif %}

    {% for num in paginator.page_range %}
    {% if page_obj.number == num %}
    <li class="page-item active">
      <a class="page-link">
        {{ num }}
        <span class="sr-only">(current)</span>
      </a>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

mysite/blog/templates/blog/snippets/search_form.html
<!-- blog/templates/blog/snippets/search_form.html -->

<form class="form-inline my-2 my-lg-0" action="{% url 'blog:search_post' %}" method="GET">
  <input class="form-control mr-sm-2" type="search" name="q" value="{{ request.GET.q }}" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
</form>

mysite/blog/templates/blog/snippets/sidebar.html
<div class="card mb-3">
  <div class="card-header">
    カテゴリ
  </div>
  <ul class="list-group list-group-flush">
    {% for category in categories|dictsort:"id" %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'blog:category_post' category.slug %}" class="card-link">{{ category.name }}</a>
      <span class="badge badge-primary badge-pill">{{ category.num_posts }}</span>
    </li>
    {% endfor %}
  </ul>
</div>

<div class="card">
  <div class="card-header">
    タグ
  </div>
  <ul class="list-group list-group-flush">
    {% for tag in tags|dictsortreversed:"num_posts"|slice:":5" %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <a href="{% url 'blog:tag_post' tag.slug %}" class="card-link">{{ tag.name }}</a>
      <span class="badge badge-primary badge-pill">{{ tag.num_posts }}</span>
    </li>
    {% endfor %}
  </ul>
  <div class="card-body text-center">
    <a href="{% url 'blog:tag_list' %}" class="card-link">すべてのタグを見る</a>
  </div>
</div>

mysite/blog/templates/blog/tag_list.html
<!-- blog/tag_list.html -->

<h1>タグ一覧</h1>
<ul>
  {% for tag in object_list %}
 <li><a href="{% url 'blog:tag_post' tag.slug %}">{{ tag.name }} ({{ tag.num_posts }})</a></li>
  {% empty %}
  <li>タグはありません。</li>
  {% endfor %}
</ul>

mysite/blog/templates/blog/tag_list_spare.html
<!-- blog/tag_list.html -->

<h1>タグ一覧</h1>
<ul>
  {% for tag in object_list %}
 <li><a href="{% url 'blog:tag_post' tag.slug %}">{{ tag.name }} ({{ tag.num_posts }})</a></li>
  {% empty %}
  <li>タグはありません。</li>
  {% endfor %}
</ul>

mysite/blog/templates/blog/tag_post.html
<!-- blog/tag_post.html -->

<h1>「#{{ tag.name }}」の投稿一覧</h1>
<ul>
  {% for post in object_list %}
  {% if user.is_authenticated or post.is_public %}
  <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></li>
  {% else %}
  <li>投稿はありません。</li>
  {% endif %}
  {% empty %}
  <li>まだ投稿はありません。</li>
  {% endfor %}

</ul>

mysite/blog/templates/blog/tag_post_spare.html
<!-- blog/tag_post.html -->

<h1>「#{{ tag.name }}」の投稿一覧</h1>
<ul>
  {% for post in object_list %}
  {% if user.is_authenticated or post.is_public %}
  <li>{% if not post.is_public %}[下書き] {% endif %}<a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></li>
  {% else %}
  <li>投稿はありません。</li>
  {% endif %}
  {% empty %}
  <li>まだ投稿はありません。</li>
  {% endfor %}

</ul>

mysite/templates/base.html
<!-- templates/base.html -->

{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}MyBlog{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">

   <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
  {% include "base/navbar.html" %}
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

mysite/templates/base/base2.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

    <title>{% block title %}Hello, world!{% endblock %}</title>
      <meta name="description" content="{% block description %}{% endblock %}">
  </head>
  <body>
      {% block content %}
    {% endblock %}
    <h1>Hello, world!</h1>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
  </body>
</html>

mysite/templates/base/navbar.html
<!-- templates/base/navbar.html -->

<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <a class="navbar-brand" href="/">MyBlog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>